version: '2.1'

services:
  mapanything:
    image: mapanything
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 443:443
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js